services:
  app:
    build:
      context: .
      dockerfile: Dockerfile      
    container_name: laravel81
    ports:
      - "80:80"    
      - "5173:5173"  
    volumes:
      - .:/var/www/html      
      - /var/www/html/vendor
      - /var/www/html/node_modules
    command: bash -c   /var/www/html/start.sh
    env_file: .env    
